sudo: required

language: go

services:
  - docker

script: 
  - go get -t -v ./...
  - go test -v ./...
  - sh ./build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t coveo/scrumpolice .;
    docker tag coveo/scrumpolice coveo/scrumpolice:latest;
    docker push coveo/scrumpolice:latest;
    fi
