sudo: required

language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on CGO_ENABLED=0

before_script:
  - go test ./...

services:
  - docker

script:
  - go get -t -v ./...
  - go test -v ./...
  - sh ./build.sh

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t coveo/scrumpolice .;
    docker tag coveo/scrumpolice coveo/scrumpolice:latest;
    docker push coveo/scrumpolice:latest;
    fi
